services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
      - '587:587'
    env_file: .env
    volumes:
      - ./converter:/converter

    command: >
      sh -c 'python manage.py runserver  0.0.0.0:8000'

    depends_on:
      - database
      - redis

  database:
    image: postgres:15.4-alpine3.18
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.1-alpine
    hostname: redis
    volumes:
      - /var/lib/redis/data/

  celery:
    build: .
    command: >
       sh -c "celery -A converter converter -l info"
    volumes:
      - ./converter:/converter
    depends_on:
      - redis
    env_file: .env
  celery-beat:
    build: .
    command: celery -A converter beat -l info
    volumes:
      - ./converter:/converter
    depends_on:
      - redis

  flower:
    build: .
    command: celery -A converter flower
    volumes:
      - ./converter:/converter
    depends_on:
      - redis
    ports:
      - '5555:5555'


volumes:
  postgres_data:
